image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: 'Upload'
          script:
            - apt-get update
            - apt-get install -y zip
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.15
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn
            - yarn build
            - zip -r --symlinks application.zip .
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: 'pinely-erzy-landing'
                COMMAND: 'upload-only'
                ZIP_FILE: 'application.zip'
                S3_BUCKET: 'elasticbeanstalk-eu-west-3-727754594471'
                VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
      - step:
          name: 'Deploy'
          deployment: staging
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: 'pinely-erzy-landing'
                COMMAND: 'deploy-only'
                VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
                ENVIRONMENT_NAME: 'Pinelyerzylanding-env'
                WAIT: 'true'
